name: deploy-to-prod
on: [push]
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: git pull origin main
      - run: tsc -p tsconfig.json
      - run: pm2 restart 0
